/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PipewireAudioBridge */

#ifndef _Included_PipewireAudioBridge
#define _Included_PipewireAudioBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PipewireAudioBridge
 * Method:    connect
 * Signature: (LISoundListner;)V
 */
JNIEXPORT void JNICALL Java_PipewireAudioBridge_connect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     PipewireAudioBridge
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PipewireAudioBridge_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
