/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_com_gammingsolution_audio_PipewireAudioBridge */

#ifndef _Included_br_com_gammingsolution_audio_PipewireAudioBridge
#define _Included_br_com_gammingsolution_audio_PipewireAudioBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_com_gammingsolution_audio_PipewireAudioBridge
 * Method:    connect
 * Signature: (Lbr/com/gammingsolution/audio/ISoundListner;)V
 */
JNIEXPORT void JNICALL Java_br_com_gammingsolution_audio_PipewireAudioBridge_connect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     br_com_gammingsolution_audio_PipewireAudioBridge
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_com_gammingsolution_audio_PipewireAudioBridge_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
