/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_com_gammingsolution_virtualgamepad_VirtualGamepadBridge */

#ifndef _Included_br_com_gammingsolution_virtualgamepad_VirtualGamepadBridge
#define _Included_br_com_gammingsolution_virtualgamepad_VirtualGamepadBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_com_gammingsolution_virtualgamepad_VirtualGamepadBridge
 * Method:    createVirtualGamepad
 * Signature: ()Lbr/com/gammingsolution/virtualgamepad/model/GamepadNative;
 */
JNIEXPORT jobject JNICALL Java_br_com_gammingsolution_virtualgamepad_VirtualGamepadBridge_createVirtualGamepad
  (JNIEnv *, jobject);

/*
 * Class:     br_com_gammingsolution_virtualgamepad_VirtualGamepadBridge
 * Method:    destroyVirtualGamepad
 * Signature: (Lbr/com/gammingsolution/virtualgamepad/model/GamepadNative;)V
 */
JNIEXPORT void JNICALL Java_br_com_gammingsolution_virtualgamepad_VirtualGamepadBridge_destroyVirtualGamepad
  (JNIEnv *, jobject, jobject);

/*
 * Class:     br_com_gammingsolution_virtualgamepad_VirtualGamepadBridge
 * Method:    sendEvent
 * Signature: (Lbr/com/gammingsolution/virtualgamepad/model/GamepadNative;J)V
 */
JNIEXPORT void JNICALL Java_br_com_gammingsolution_virtualgamepad_VirtualGamepadBridge_sendEvent
  (JNIEnv *, jobject, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
